# Generated by Django 2.2.10 on 2020-05-17 01:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='slug',
            field=models.SlugField(default=uuid.uuid1, unique=True),
        ),
    ]
