# Generated by Django 2.2.10 on 2020-05-18 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200518_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(default='No description available', null=True),
        ),
    ]
