# Generated by Django 2.2.10 on 2020-05-18 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200518_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='size',
            field=models.ManyToManyField(to='core.Size'),
        ),
    ]
