# Generated by Django 2.2.10 on 2020-05-21 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_item_in_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='comment',
            field=models.CharField(default='NA', max_length=200),
        ),
        migrations.AddField(
            model_name='order',
            name='customer_name',
            field=models.CharField(default='NA', max_length=200),
        ),
        migrations.AlterField(
            model_name='shop',
            name='slug',
            field=models.SlugField(verbose_name='Shop URL'),
        ),
    ]
