# Generated by Django 2.2.10 on 2020-05-21 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20200522_0514'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='being_packed',
            field=models.BooleanField(default=False, verbose_name='Packing Status'),
        ),
        migrations.AlterField(
            model_name='order',
            name='being_delivered',
            field=models.BooleanField(default=False, verbose_name='Shiping Status'),
        ),
        migrations.AlterField(
            model_name='order',
            name='received',
            field=models.BooleanField(default=False, verbose_name='Received '),
        ),
    ]
