# Generated by Django 2.2.10 on 2020-05-23 02:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20200522_0641'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='shop_type',
        ),
        migrations.AddField(
            model_name='shop',
            name='shop_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.ShopType'),
        ),
    ]
