# Generated by Django 2.2.10 on 2020-06-13 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20200609_1003'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='test'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shop',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Shop URL'),
        ),
    ]
