# Generated by Django 2.2.10 on 2020-06-16 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20200614_0140'),
    ]

    operations = [
        migrations.CreateModel(
            name='RootCat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, default='ps/5.png', null=True, upload_to='rootcat')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='category',
            name='tags',
            field=models.CharField(default='NA', max_length=500),
            preserve_default=False,
        ),
    ]
