# Generated by Django 2.2.10 on 2020-06-16 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20200616_1634'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rootcat',
            old_name='name',
            new_name='title',
        ),
    ]
