# Generated by Django 2.2.10 on 2020-07-22 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20200616_2357'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='thumb',
            field=models.ImageField(blank=True, null=True, upload_to='products/thumb/'),
        ),
    ]
