# Generated by Django 2.2.10 on 2020-05-14 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='date_created',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='shop_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
