# Generated by Django 2.2.10 on 2020-05-16 20:52

from django.db import migrations, models
import shop.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20200514_1912'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload', models.FileField(upload_to=shop.models.user_directory_path)),
            ],
        ),
        migrations.RemoveField(
            model_name='shop',
            name='user',
        ),
        migrations.AlterField(
            model_name='shop',
            name='shop_image',
            field=models.ImageField(blank=True, null=True, upload_to='documents/%Y/%m/%d/'),
        ),
    ]
